### ISSUE TITLE
perl magick not available

### ISSUE THREAD

**Issue by esdoublelef** [cyberang3l/timelapse-deflicker#11]
Hi, 

I use windows 10 and I have installed ActivePerl 

however it seems that I am unable to install the modules as stated libfile-type-perl libterm-progressbar-perl perlmagick libimage-exiftool-perl.

Please excuse me as I am new to Perl.

I use ImageMagick.exe together with a .batch file for all my usual processing. I was wondering if the de-flicker codes can be adapted to .batch format so that it can run like the way you intended it. I tried to understand the code you've written but I am not experienced enough to convert it to the batch file code.

or if you know how I may install the required modules to run this perl?

thank you, and I appreciate any help!

**Comment by cyberang3l** [comment]
Hi,

I have never tested this script in Windows nor do I have a clue how can one install the necessary perl modules in Windows.
Sorry, but I can't help much here :(

If you manage to get it working and want to share the information I would be happy to update the readme file with the necessary instructions.
