### ISSUE TITLE
work with raw files

### ISSUE THREAD

**Issue by dieseld2** [cyberang3l/timelapse-deflicker#4]
Hi there,
Is it possible to run this script with raw files?
I saw Image-ExifTool can work with many raw files from any camera.

**Comment by cyberang3l** [comment]
Unfortunately the script does not work on raw files.

Image-ExitTool that you mention, only extracts metadata information from the image.

It is imagemagick used by this script to find the average luminance and change the brightness of an image.

**Comment by mattpopovich** [comment]
For anyone else coming across this and has the same question, I had some success converting my raw files to `.tiff` and then to `.png`. 

`timelapse-deflicker.pl` can operate on `.png` files.

```bash
for file in *.dng; do
  echo "Processing $file..."
  dcraw -T -6 -W "$file"
  convert "${file%.dng}.tiff" -depth 16 PNG:"${file%.dng}.png"
  rm "${file%.dng}.tiff"
done
```

Apparently `.tiff` can be lossless and supports 16-bits. As can `.png`.
