### ISSUE TITLE
Feature request / question: White balance adjustment

### ISSUE THREAD

**Issue by jchnkl** [cyberang3l/timelapse-deflicker#8]
Hi,

I have a lot (color) flickering due to white balance changes. Would it be possible to implement adjustment of white balance values? Or even white balance ramping?

Thank you very much!

**Comment by cyberang3l** [comment]
I assume this would be a bit trickier than just changing the brightness as in order to change the white balance I need to change the RGB colors of the image. That's 3 a dimensional problem. I will need to study a little bit for this and see how hard would that be to implement :)

**Comment by jchnkl** [comment]
Thanks for looking into this! :)
However, I'm closing this issue, because in the meantime I implemented my own White Balance ramping / smoothing solution, based on darktable.

https://gitlab.com/jochen.keil/timelapse-smooth-wb
