### ISSUE TITLE
No Effect

### ISSUE THREAD

**Issue by muessjoeh** [cyberang3l/timelapse-deflicker#9]
The program shows no effect for me. I think that the variables low_window and high_window have the same value (defined in lines 249 and 250):
  my $low_window  = int( $RollingWindow / 2 );
  my $high_window = $RollingWindow - $low_window;

**Comment by cyberang3l** [comment]
That's correct. These are the same only for even rolling windows (2,4,6,8,10,...). If you ask for an odd rolling window (1,3,5,7,9,11,...) then `high_window = low_window + 1` as you cannot have non-integer windows.

Keep in mind that this script is changing the average brightness of each picture. So if you have some extreme variations in your pictures (e.g. a bright blinking light), the script will perform poorly.

I would suggest you to try different rolling window sizes and number of passes.
